# Generated by Django 5.2.6 on 2025-10-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_receipt_order_refunded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
