# Generated by Django 5.2.6 on 2025-10-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
