# Generated by Django 5.2.6 on 2025-10-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='original_price',
            field=models.IntegerField(null=True),
        ),
    ]
