# Generated by Django 5.2.6 on 2025-10-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_transaction_delete_bankaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
