# Generated by Django 5.2.6 on 2025-10-22 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
    ]
