# Generated by Django 5.2.6 on 2025-10-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_remove_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='estimated_delivery_date_down',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='estimated_delivery_date_up',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
