# Generated by Django 5.2.6 on 2025-11-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_orderitem_estimated_delivery_date_down_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(max_length=100),
        ),
    ]
