# Generated by Django 5.2.6 on 2025-10-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_vendorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
