# Generated by Django 5.2.6 on 2025-10-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_vendorprofile_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
