# Generated by Django 5.2.6 on 2025-10-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_vendorprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='reason_for_rejection',
            field=models.TextField(blank=True, null=True),
        ),
    ]
