# Generated by Django 5.2.6 on 2025-11-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='discount_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
