# Generated by Django 5.2.6 on 2025-11-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_banner_discount_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('Main Banner', 'Main'), ('Side Banner', 'Side')], default='Main Banner', max_length=15),
        ),
    ]
