# Generated by Django 5.2.6 on 2025-11-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_banner_banner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('Main', 'Main'), ('Side', 'Side')], default='Main', max_length=15),
        ),
    ]
