# Generated by Django 5.2.6 on 2025-09-26 00:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='file_url',
        ),
        migrations.AddField(
            model_name='upload',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
