# Generated by Django 5.2.6 on 2025-10-12 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_remove_upload_file_name_remove_upload_file_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='user',
        ),
    ]
