# Generated by Django 5.2.6 on 2025-09-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productreview_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_best_seller',
        ),
        migrations.AddField(
            model_name='product',
            name='sale_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
