# Generated by Django 5.2.6 on 2025-09-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_is_best_seller_product_sale_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_product_on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
