# Generated by Django 5.2.6 on 2025-09-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_is_product_on_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_product_on_sale',
            new_name='add_product_to_sales',
        ),
    ]
