# Generated by Django 5.2.6 on 2025-09-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_is_product_on_sale_product_add_product_to_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deal_of_the_day',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
