# Generated by Django 5.2.6 on 2025-10-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_wishlist_product_alter_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
