# Generated by Django 5.2.6 on 2025-11-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_to_deal_of_the_day',
            field=models.BooleanField(default=False),
        ),
    ]
